release-windows-package: sync with 4.8 branch

diff --git a/maintainer/release-windows-packages b/maintainer/release-windows-packages
--- a/maintainer/release-windows-packages
+++ b/maintainer/release-windows-packages
@@ -37,12 +37,24 @@ oscoptions="-A https://api.opensuse.org"
 apitoken=cli-uxo23l4q5qrzoyscbz5kp4zcngqp
 options='projectPHIDs[]=PHID-PROJ-3qa4tomwgrmcmp4ym2ow'
 
+# abort on errors
+set -e
+
+echo2() { printf "%s\n" "$*" >&2; }
+
+which 7z >/dev/null 2>&1
+if test $? -ne 0; then
+    echo "7z not found, run 'zypper install p7zip'"
+    exit 1
+fi
+
 self=$(realpath $0)
 
 if ! test -d "work"; then
     mkdir work
 fi
 
+echo2 "running mode $1"
 dryrun=0
 update=0
 update_symlink=0
@@ -62,6 +74,11 @@ case $var in
 	use32=0
 	usesrc=0
 	update=1
+	shift
+	;;
+
+--symlink) ## update 'latest' symbolic link
+	update_symlink=1
 	shift
 	;;
 
@@ -176,16 +193,17 @@ function upload() {
 
 function createdescription() {
 	getversion
-	description="Please move the $RELEASE_NAME related files which has been uploaded to upload.kde.org/incoming to download mirror 'stable/$RELEASE_NAME/$VERSION' location"
+	description="Please move the $RELEASE_NAME related files which have been uploaded to upload.kde.org/incoming to download mirror 'stable/$RELEASE_NAME/$VERSION' location"
 	if test $update -eq 1; then
 		description="$description and remove the old files from this directory."
 	elif test $update_symlink -eq 1; then
-		description="$description and update the symbolic link 'stable/$RELEASE_NAME/latest' to 'stable/$RELEASE_NAME/$VERSION'"
+		description="$description and update the symbolic link 'stable/$RELEASE_NAME/latest' to 'stable/$RELEASE_NAME/$VERSION'."
 	else
 		description="$description."
 	fi
 	sums=$(cat work/out/$NAME.sha256sum | gawk 'BEGIN { print "dir	 shasum								   file"}  $2 ~ /mingw32/ { print "win32 " $0 } $2 ~ /mingw64/ { print "win64 " $0 } $2 ~ /\-src/ { print "src   " $0 }')
 	echo -e "$description\n\n$sums" > work/description
+	cat work/description
 	touch work/$1.finished
 }
 
